/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pelicula;

import ClasesGlobales.CRUD;
import ClasesGlobales.ConexionBD;
import ClasesGlobales.TablaGestion;
import ClasesInterfaz.TitulosSala;
import Sala.SalaClass;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Pelicula extends javax.swing.JInternalFrame {

    private PeliculaClass pelicula;
    private CRUD crud;
    private int last = 0;
   
    
    
    public Pelicula() {
        initComponents();
        setTitle("Peliculas");
        crud.InstanciarCRUD();
        nombrepeli.setEnabled(false);
        fechaestreno.setEnabled(false);
        duracion.setEnabled(false);
        imagen.setEnabled(false);
        categoria.setEnabled(false);
        clasificacion.setEnabled(false);
        idioma.setEnabled(false);
        pelicula = new PeliculaClass();
        guardapeli.setVisible(false);
        confirmareli.setVisible(false);
        paceptar.setVisible(false);
        peliminar.setVisible(false);
        pcancelaraccion.setVisible(false);
        ccancelar.setVisible(false);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelGeneral = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        registrapeli = new javax.swing.JLabel();
        guardapeli = new javax.swing.JLabel();
        eliminapeli = new javax.swing.JLabel();
        confirmareli = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        paceptar = new javax.swing.JLabel();
        peliminar = new javax.swing.JLabel();
        pcancelaraccion = new javax.swing.JLabel();
        ccancelar = new javax.swing.JLabel();
        panelCentral = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        nombrepeli = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fechaestreno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        duracion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        imagen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        categoria = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        clasificacion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        idioma = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        panelGeneral.setLayout(new java.awt.BorderLayout());

        panelSuperior.setBackground(new java.awt.Color(29, 45, 80));

        registrapeli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo_registro.png"))); // NOI18N
        registrapeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarpelicula(evt);
            }
        });

        guardapeli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aceptar.png"))); // NOI18N
        guardapeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarpelicula(evt);
            }
        });

        eliminapeli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar_registro.png"))); // NOI18N
        eliminapeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarPelicula(evt);
            }
        });

        confirmareli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aceptar.png"))); // NOI18N
        confirmareli.setText("jLabel10");
        confirmareli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AceptarEliminacion(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Añadir");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Eliminar");

        paceptar.setForeground(new java.awt.Color(255, 255, 255));
        paceptar.setText("Aceptar");

        peliminar.setForeground(new java.awt.Color(255, 255, 255));
        peliminar.setText("Aceptar");

        pcancelaraccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        pcancelaraccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pcancelaraccionMouseClicked(evt);
            }
        });

        ccancelar.setForeground(new java.awt.Color(255, 255, 255));
        ccancelar.setText("Cancelar");

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorLayout.createSequentialGroup()
                        .addComponent(registrapeli)
                        .addGap(33, 33, 33)))
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addComponent(eliminapeli, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pcancelaraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ccancelar)
                        .addGap(47, 47, 47)))
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(paceptar)
                        .addGap(47, 47, 47)
                        .addComponent(peliminar))
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addComponent(guardapeli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmareli, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(487, 487, 487))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmareli, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorLayout.createSequentialGroup()
                        .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(guardapeli, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eliminapeli, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registrapeli, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pcancelaraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)
                            .addComponent(paceptar)
                            .addComponent(peliminar)
                            .addComponent(ccancelar))))
                .addContainerGap())
        );

        panelGeneral.add(panelSuperior, java.awt.BorderLayout.PAGE_START);

        panelCentral.setLayout(new java.awt.CardLayout());

        jPanel4.setBackground(new java.awt.Color(30, 95, 116));

        nombrepeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrepeliActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha Estreno:");

        fechaestreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaestrenoActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Duración:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Imagen:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Categoría:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Clasificación:");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Idioma:");

        jLabel9.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Registrar Nueva Película");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jLabel9))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombrepeli, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fechaestreno, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(204, 204, 204)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idioma, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(440, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel9)
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrepeli, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fechaestreno, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(clasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(idioma, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(394, Short.MAX_VALUE))
        );

        panelCentral.add(jPanel4, "card2");

        panelGeneral.add(panelCentral, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(panelGeneral);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarpelicula(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarpelicula
       
      String query;  
        
      pelicula.setNombrePeli(nombrepeli.getText());
      pelicula.setFechaEstreno(fechaestreno.getText());
      pelicula.setDuracion(duracion.getText());
      pelicula.setImagen(imagen.getText());
      pelicula.setCategoria(categoria.getText());
      pelicula.setClasificacion(clasificacion.getText());
      pelicula.setIdioma(idioma.getText());
     
      pelicula.actualizarValues();
      query = pelicula.getAdminConsulta().queryInsertar(pelicula.getValues(), pelicula.getParametros(), pelicula.getNombre());
      System.out.println(query);
      crud.InstanciarCRUD().EjecutarInstruccion(query);
        nombrepeli.setEnabled(false);
        fechaestreno.setEnabled(false);
        duracion.setEnabled(false);
        imagen.setEnabled(false);
        categoria.setEnabled(false);
        clasificacion.setEnabled(false);
        idioma.setEnabled(false);
        guardapeli.setVisible(false);
        nombrepeli.setText("");
        fechaestreno.setText("");
        duracion.setText("");
        imagen.setText("");
        categoria.setText("");
        clasificacion.setText("");
        idioma.setText("");
        paceptar.setVisible(false);
    }//GEN-LAST:event_guardarpelicula

    private void registrarpelicula(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarpelicula
        last = 1;
        nombrepeli.setEnabled(true);
        fechaestreno.setEnabled(true);
        duracion.setEnabled(true);
        imagen.setEnabled(true);
        categoria.setEnabled(true);
        clasificacion.setEnabled(true);
        idioma.setEnabled(true);
        guardapeli.setVisible(true);
        paceptar.setVisible(true);
        pcancelaraccion.setVisible(true);
        ccancelar.setVisible(true);
    }//GEN-LAST:event_registrarpelicula

    private void fechaestrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaestrenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaestrenoActionPerformed

    private void nombrepeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrepeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrepeliActionPerformed

    private void EliminarPelicula(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarPelicula
      last = 2;
      nombrepeli.setEnabled(true);
      confirmareli.setVisible(true);
      peliminar.setVisible(true);
      pcancelaraccion.setVisible(true);
      ccancelar.setVisible(true);
    }//GEN-LAST:event_EliminarPelicula

    private void AceptarEliminacion(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AceptarEliminacion
      pelicula.getAdminConsulta().setWhere("where nombre ='" + nombrepeli.getText() +"'");
      String query = pelicula.getAdminConsulta().queryEliminar(pelicula.getNombre());
      crud.InstanciarCRUD().EjecutarInstruccion(query);
      nombrepeli.setEnabled(false);
      nombrepeli.setText("");
      confirmareli.setVisible(false);
      peliminar.setVisible(false);
    }//GEN-LAST:event_AceptarEliminacion

    private void pcancelaraccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pcancelaraccionMouseClicked
       if (last == 1){
        nombrepeli.setEnabled(false);
        fechaestreno.setEnabled(false);
        duracion.setEnabled(false);
        imagen.setEnabled(false);
        categoria.setEnabled(false);
        clasificacion.setEnabled(false);
        idioma.setEnabled(false);
        guardapeli.setVisible(false);
        nombrepeli.setText("");
        fechaestreno.setText("");
        duracion.setText("");
        imagen.setText("");
        categoria.setText("");
        clasificacion.setText("");
        idioma.setText("");
        paceptar.setVisible(false);
        pcancelaraccion.setVisible(false);
        ccancelar.setVisible(false);
           
           
       }
       else if(last == 2){
      nombrepeli.setEnabled(false);
      nombrepeli.setText("");
      confirmareli.setVisible(false);
      peliminar.setVisible(false);
      pcancelaraccion.setVisible(false);
      ccancelar.setVisible(false);
       }
       
       else{
           System.out.println("no se puede completar acción");
       }
    }//GEN-LAST:event_pcancelaraccionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField categoria;
    private javax.swing.JLabel ccancelar;
    private javax.swing.JTextField clasificacion;
    private javax.swing.JLabel confirmareli;
    private javax.swing.JTextField duracion;
    private javax.swing.JLabel eliminapeli;
    private javax.swing.JTextField fechaestreno;
    private javax.swing.JLabel guardapeli;
    private javax.swing.JTextField idioma;
    private javax.swing.JTextField imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombrepeli;
    private javax.swing.JLabel paceptar;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JLabel pcancelaraccion;
    private javax.swing.JLabel peliminar;
    private javax.swing.JLabel registrapeli;
    // End of variables declaration//GEN-END:variables
}
