/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JframeVenta;

import Cartelera.ObtenerPeliculas;
import ClasesGlobales.CRUD;
import ClasesVenta.Asiento;
import ClasesVenta.AsientoSQL;
import ClasesVenta.Cliente;
import ClasesVenta.ClientesSQL;
import ClasesVenta.Factura;
import ClasesVenta.FuncionesSQL;
import Funcion.FuncionClass;
import Pelicula.*;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import java.awt.BorderLayout;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class JVentas extends javax.swing.JInternalFrame {

    public static javax.swing.JLabel aa1;
    private CRUD c;
    private ClientesSQL obtener;
    private Factura factura;
    private Asiento silla;
    private ArrayList<Cliente> clientes;
    private Cliente cliente;
    private FuncionClass funcion;
    private ArrayList<Asiento> asientoss;
    public AsientoSQL obetenerAsientos;

    public JVentas() {
        initComponents();
        setTitle("Peliculas");
        c = c.InstanciarCRUD();
        //se le manda el combo, la consulta, y el nombre de la columna 
        c.InstanciarCRUD().llenar_combo(JPelicula, "SELECT p.nombre FROM funcion AS f \n"
                + "INNER JOIN sala AS s ON s.idSala = f.Sala_idSala\n"
                + "INNER JOIN pelicula AS p ON p.idPelicula = f.Pelicula_idPelicula GROUP BY p.nombre;", "nombre");
        c.InstanciarCRUD().llenar_combo(Jsala, "SELECT s.num_sala FROM funcion AS f \n"
                + "INNER JOIN sala AS s ON s.idSala = f.Sala_idSala\n"
                + "INNER JOIN pelicula AS p ON p.idPelicula = f.Pelicula_idPelicula GROUP BY s.num_sala;", "num_sala");
        c.InstanciarCRUD().llenar_combo(Jfila, "SELECT a.fila FROM asiento AS a GROUP BY fila;", "fila");
        c.InstanciarCRUD().llenar_combo(Jcolumna, "SELECT a.columna FROM asiento AS a GROUP BY columna ORDER BY columna asc;", "columna");
        rcliente.setVisible(false);
        factura = new Factura();
        cliente = new Cliente();
        silla = new Asiento();
        obetenerAsientos = new AsientoSQL();
    }

    public void generarFactura() {
        
        System.out.println("hola");
    }

    public void abrir(String name) throws IOException {
        File path = new File(name + ".pdf");
        Desktop.getDesktop().open(path);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelGeneral = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        facturacion = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        nit = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        Jsala = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        JPelicula = new javax.swing.JComboBox<>();
        total = new javax.swing.JLabel();
        rcliente = new javax.swing.JButton();
        validarcliente = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        Jcolumna = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        Jfila = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        panelGeneral.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(30, 95, 116));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        facturacion.setBackground(new java.awt.Color(243, 234, 232));
        facturacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel17.setText("Telefono:");
        facturacion.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 70, 20));

        jLabel18.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel18.setText("Nombre:");
        facturacion.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 60, 20));

        jLabel20.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel20.setText("Nit:");
        facturacion.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 30, 20));

        telefono.setEditable(false);
        telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoActionPerformed(evt);
            }
        });
        facturacion.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 230, -1));

        nit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nitActionPerformed(evt);
            }
        });
        facturacion.add(nit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 160, -1));

        nombre.setEditable(false);
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        facturacion.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 230, -1));

        Jsala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JsalaActionPerformed(evt);
            }
        });
        facturacion.add(Jsala, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 200, 30));

        jLabel23.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel23.setText("Sala:");
        facturacion.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel24.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel24.setText("Pelicula:");
        facturacion.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        JPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPeliculaActionPerformed(evt);
            }
        });
        facturacion.add(JPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 200, 30));

        total.setBackground(new java.awt.Color(102, 102, 102));
        total.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        total.setText("#000");
        facturacion.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 80, 50));

        rcliente.setBackground(new java.awt.Color(226, 235, 240));
        rcliente.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        rcliente.setText("Registrar Cliente");
        rcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rclienteActionPerformed(evt);
            }
        });
        facturacion.add(rcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 140, 40));

        validarcliente.setBackground(new java.awt.Color(226, 235, 240));
        validarcliente.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        validarcliente.setText("Validar NIT");
        validarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validarclienteActionPerformed(evt);
            }
        });
        facturacion.add(validarcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 110, 40));

        cancelar.setBackground(new java.awt.Color(226, 235, 240));
        cancelar.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        facturacion.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, 130, 40));

        aceptar.setBackground(new java.awt.Color(255, 255, 255));
        aceptar.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        facturacion.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 130, 40));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel21.setText("Columna:");
        facturacion.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 70, 30));

        Jcolumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcolumnaActionPerformed(evt);
            }
        });
        facturacion.add(Jcolumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 140, 30));

        jLabel25.setBackground(new java.awt.Color(0, 0, 0));
        jLabel25.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel25.setText("Fila:");
        facturacion.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 40, 30));

        Jfila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JfilaActionPerformed(evt);
            }
        });
        facturacion.add(Jfila, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 140, 30));

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel26.setText("Total: Q");
        facturacion.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 100, 50));

        jLabel27.setBackground(new java.awt.Color(0, 0, 0));
        jLabel27.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 153, 0));
        jLabel27.setText("VENTA DE BOLETOS");
        facturacion.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 190, 50));
        facturacion.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 190, 10));

        jPanel1.add(facturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 600, 640));

        panelGeneral.add(jPanel1, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(panelGeneral);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        String asiento = (String) Jfila.getSelectedItem() + (String) Jcolumna.getSelectedItem();
        String fila =(String) Jfila.getSelectedItem();
        String sala =(String) Jsala.getSelectedItem();
        String columna = (String) Jcolumna.getSelectedItem();
        if (nit.getText().equals("") || nombre.getText().equals("") || telefono.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios");
        } else {
            String seleccionSala = (String) Jsala.getSelectedItem();

            //seleccion de disponibilidad del asiento
            String dispo = c.InstanciarCRUD().getValor("SELECT a.disponible FROM asiento AS a WHERE a.fila= '" + fila + "' AND  a.columna = '" + columna + "' AND a.Sala_idSala = '" + sala +"';", "disponible");
            System.out.println(fila+columna);
            if ("1".equals(dispo)) {

                String seleccionPelicula = (String) JPelicula.getSelectedItem();

                String query;
                float f = Float.parseFloat(total.getText());
                factura.setTotal(f);
                factura.setDetalle("NIT: " + nit.getText() + " \n"
                        + "Cliente: " + nombre.getText() + " \n"
                        + "Sala: " + seleccionSala
                        + "\nPelicula: " + seleccionPelicula
                        + "\nAsiento: " + asiento
                        + "\nTotal: Q" + f);
                //obtener la fecha y hora
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
                String detalle = "NIT: " + nit.getText() + " \n"
                        + "Cliente: " + nombre.getText() + " \n"
                        + "Sala: " + seleccionSala
                        + "\nPelicula: " + seleccionPelicula
                        + "\nAsiento: " + asiento
                        + "\nTotal: Q" + f
                        + "\nFecha de emicion de Factura: " + dtf.format(LocalDateTime.now());
                factura.actualizarValues();
                query = factura.getAdminConsulta().queryInsertar(factura.getValues(), factura.getParametros(), factura.getNombre());
                c.InstanciarCRUD().EjecutarInstruccion(query);
                
                //consulta para cambiar la disponibilidad del asiento a opcupado
                String query2;
                silla.setIdAsiento(asiento);
                silla.setDisponible(false);
                silla.actualizarValues();
                silla.getAdminConsulta().setWhere("WHERE fila = '" + fila + "' AND columna = '"+columna+"'");
                query2 = silla.getAdminConsulta().queryModificar("asiento", "SET disponible = 0 ");
                c.InstanciarCRUD().EjecutarInstruccion(query2);

                //generamos la facura para que se abra automaticamente

                nombre.setText("");
                telefono.setText("");
                try {
                    abrir(nit.getText());
                } catch (IOException ex) {
                    Logger.getLogger(JVentas.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "El asiento seleccionado no esta disponible");
            }

        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void validarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validarclienteActionPerformed
        if (nit.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Paraemtros invalidos");
        } else {
            obtener = new ClientesSQL();
            System.out.println(nit.getText());
            this.clientes = obtener.obtenerClientes("SELECT c.nombre, c.nit, c.telefono FROM cliente AS c WHERE c.nit = '" + nit.getText() + "';");
            System.out.println(clientes.size() + "valio");
            int size = clientes.size();
            if (size != 0) {
                for (int i = 0; i < clientes.size(); i++) {
                    nombre.setText(clientes.get(i).getNombrec());
                    telefono.setText(clientes.get(i).getTelefono());

                }
            } else {
                nombre.setEditable(true);
                telefono.setEditable(true);
                rcliente.setVisible(true);
                JOptionPane.showMessageDialog(null, "No existe el cliente, Registre al nuevo cliente");
            }
        }
    }//GEN-LAST:event_validarclienteActionPerformed

    private void rclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rclienteActionPerformed
        if (nit.getText().equals("") || nombre.getText().equals("") || telefono.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Hay campos vacios");
        } else {
            String query;
            cliente.setNIT(nit.getText());
            cliente.setNombrec(nombre.getText());
            cliente.setTelefono(telefono.getText());
            cliente.actualizarValues();

            query = cliente.getAdminConsulta().queryInsertar(cliente.getValues(), cliente.getParametros(), cliente.getNombre());
            c.InstanciarCRUD().EjecutarInstruccion(query);
            nombre.setText("");
            telefono.setText("");
        }
    }//GEN-LAST:event_rclienteActionPerformed

    private void JPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPeliculaActionPerformed
        String seleccionPelicula = (String) JPelicula.getSelectedItem();
        total.setText(c.InstanciarCRUD().getValor("select f.Precio from funcion as f\n"
                + "inner join sala as s on s.idSala = f.Sala_idSala\n"
                + "inner join pelicula as p on p.idPelicula = f.Pelicula_idPelicula\n"
                + "WHERE p.nombre = '" + seleccionPelicula + "';", "Precio"));
        System.out.println(seleccionPelicula);
    }//GEN-LAST:event_JPeliculaActionPerformed

    private void JsalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JsalaActionPerformed

    }//GEN-LAST:event_JsalaActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void nitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nitActionPerformed

    }//GEN-LAST:event_nitActionPerformed

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoActionPerformed

    private void JcolumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcolumnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcolumnaActionPerformed

    private void JfilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JfilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JfilaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JPelicula;
    private javax.swing.JComboBox<String> Jcolumna;
    private javax.swing.JComboBox<String> Jfila;
    private javax.swing.JComboBox<String> Jsala;
    private javax.swing.JButton aceptar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelar;
    private javax.swing.JPanel facturacion;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nit;
    private javax.swing.JTextField nombre;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JButton rcliente;
    private javax.swing.JTextField telefono;
    private javax.swing.JLabel total;
    private javax.swing.JButton validarcliente;
    // End of variables declaration//GEN-END:variables
}
