/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JframeVenta;

/**
 *
 * @author CRISTOPHERGUERRA
 */
public class Sala2 extends javax.swing.JPanel {

    /**
     * Creates new form Sala2
     */
    public Sala2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Sala1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        a4 = new javax.swing.JLabel();
        a5 = new javax.swing.JLabel();
        a6 = new javax.swing.JLabel();
        b6 = new javax.swing.JLabel();
        b5 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        c1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        c3 = new javax.swing.JLabel();
        c4 = new javax.swing.JLabel();
        c5 = new javax.swing.JLabel();
        c6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        a12 = new javax.swing.JLabel();
        a11 = new javax.swing.JLabel();
        a10 = new javax.swing.JLabel();
        a9 = new javax.swing.JLabel();
        a8 = new javax.swing.JLabel();
        a7 = new javax.swing.JLabel();
        b7 = new javax.swing.JLabel();
        b8 = new javax.swing.JLabel();
        b9 = new javax.swing.JLabel();
        b10 = new javax.swing.JLabel();
        b11 = new javax.swing.JLabel();
        b12 = new javax.swing.JLabel();
        c12 = new javax.swing.JLabel();
        c11 = new javax.swing.JLabel();
        c10 = new javax.swing.JLabel();
        c9 = new javax.swing.JLabel();
        c8 = new javax.swing.JLabel();
        c7 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sala1.setBackground(new java.awt.Color(30, 95, 116));
        Sala1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(245, 253, 255));
        jLabel3.setText("FILA \"AA\"");
        Sala1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        a1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        a1.setText("|");
        Sala1.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, 30));

        a2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        a2.setText("|");
        Sala1.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, 30));

        a3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        a3.setText("|");
        Sala1.add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, 30));

        a4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        a4.setText("|");
        Sala1.add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, 30));

        a5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        a5.setText("|");
        Sala1.add(a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, 30));

        a6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        a6.setText("|");
        Sala1.add(a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, 30));

        b6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        b6.setText("|");
        Sala1.add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, 30));

        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        b5.setText("|");
        Sala1.add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, 30));

        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        b4.setText("|");
        Sala1.add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, 30));

        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        b3.setText("|");
        Sala1.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, 30));

        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        b2.setText("|");
        Sala1.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, 30));

        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        b1.setText("|");
        Sala1.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, 30));

        jLabel16.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(245, 253, 255));
        jLabel16.setText("FILA \"BB\"");
        Sala1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        c1.setText("|");
        Sala1.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, 30));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 253, 255));
        jLabel1.setText("FILA \"CC\"");
        Sala1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        c2.setText("|");
        Sala1.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, 30));

        c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        c3.setText("|");
        Sala1.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, 30));

        c4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        c4.setText("|");
        Sala1.add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, 30));

        c5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        c5.setText("|");
        Sala1.add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, 30));

        c6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        c6.setText("|");
        Sala1.add(c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, 30));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(245, 253, 255));
        jLabel2.setText("6");
        Sala1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 20, 20));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(245, 253, 255));
        jLabel9.setText("5");
        Sala1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 20, 20));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(245, 253, 255));
        jLabel8.setText("SALA 2");
        Sala1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 50, 30));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(245, 253, 255));
        jLabel7.setText("3");
        Sala1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 20, 20));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(245, 253, 255));
        jLabel6.setText("2");
        Sala1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 20, 20));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(245, 253, 255));
        jLabel5.setText("1");
        Sala1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 20, 20));

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(245, 253, 255));
        jLabel10.setText("7");
        Sala1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 20, 20));

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(245, 253, 255));
        jLabel11.setText("8");
        Sala1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 20, 20));

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(245, 253, 255));
        jLabel12.setText("9");
        Sala1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 20, 20));

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(245, 253, 255));
        jLabel13.setText("10");
        Sala1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 20, 20));

        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(245, 253, 255));
        jLabel14.setText("11");
        Sala1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 20, 20));

        jLabel15.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(245, 253, 255));
        jLabel15.setText("12");
        Sala1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 20, 20));

        a12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        a12.setText("|");
        Sala1.add(a12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, -1, 30));

        a11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        a11.setText("|");
        Sala1.add(a11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, -1, 30));

        a10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        a10.setText("|");
        Sala1.add(a10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, 30));

        a9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        a9.setText("|");
        Sala1.add(a9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, 30));

        a8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        a8.setText("|");
        Sala1.add(a8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, 30));

        a7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        a7.setText("|");
        Sala1.add(a7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, 30));

        b7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        b7.setText("|");
        Sala1.add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, 30));

        b8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        b8.setText("|");
        Sala1.add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, 30));

        b9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        b9.setText("|");
        Sala1.add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, 30));

        b10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        b10.setText("|");
        Sala1.add(b10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, 30));

        b11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        b11.setText("|");
        Sala1.add(b11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, 30));

        b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        b12.setText("|");
        Sala1.add(b12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, 30));

        c12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        c12.setText("|");
        Sala1.add(c12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, -1, 30));

        c11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        c11.setText("|");
        Sala1.add(c11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, 30));

        c10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        c10.setText("|");
        Sala1.add(c10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, 30));

        c9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        c9.setText("|");
        Sala1.add(c9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, 30));

        c8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        c8.setText("|");
        Sala1.add(c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, 30));

        c7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        c7.setText("|");
        Sala1.add(c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, 30));

        jLabel39.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(245, 253, 255));
        jLabel39.setText("4");
        Sala1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 20, 20));

        jPanel1.add(Sala1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Sala1;
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a10;
    private javax.swing.JLabel a11;
    private javax.swing.JLabel a12;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel a5;
    private javax.swing.JLabel a6;
    private javax.swing.JLabel a7;
    private javax.swing.JLabel a8;
    private javax.swing.JLabel a9;
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b10;
    private javax.swing.JLabel b11;
    private javax.swing.JLabel b12;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JLabel b5;
    private javax.swing.JLabel b6;
    private javax.swing.JLabel b7;
    private javax.swing.JLabel b8;
    private javax.swing.JLabel b9;
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c10;
    private javax.swing.JLabel c11;
    private javax.swing.JLabel c12;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.JLabel c4;
    private javax.swing.JLabel c5;
    private javax.swing.JLabel c6;
    private javax.swing.JLabel c7;
    private javax.swing.JLabel c8;
    private javax.swing.JLabel c9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
