/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JframeVenta;

/**
 *
 * @author CRISTOPHERGUERRA
 */
public class Sala1 extends javax.swing.JPanel {

    /**
     * Creates new form Sala1
     */
    public Sala1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Sala2 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        a25 = new javax.swing.JLabel();
        a26 = new javax.swing.JLabel();
        a27 = new javax.swing.JLabel();
        a28 = new javax.swing.JLabel();
        a29 = new javax.swing.JLabel();
        a30 = new javax.swing.JLabel();
        b25 = new javax.swing.JLabel();
        b26 = new javax.swing.JLabel();
        b27 = new javax.swing.JLabel();
        b28 = new javax.swing.JLabel();
        b29 = new javax.swing.JLabel();
        b30 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        c25 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        c26 = new javax.swing.JLabel();
        c27 = new javax.swing.JLabel();
        c28 = new javax.swing.JLabel();
        c29 = new javax.swing.JLabel();
        c30 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        a31 = new javax.swing.JLabel();
        a32 = new javax.swing.JLabel();
        a33 = new javax.swing.JLabel();
        a34 = new javax.swing.JLabel();
        a35 = new javax.swing.JLabel();
        a36 = new javax.swing.JLabel();
        b31 = new javax.swing.JLabel();
        b32 = new javax.swing.JLabel();
        b33 = new javax.swing.JLabel();
        b34 = new javax.swing.JLabel();
        b35 = new javax.swing.JLabel();
        b36 = new javax.swing.JLabel();
        c31 = new javax.swing.JLabel();
        c32 = new javax.swing.JLabel();
        c33 = new javax.swing.JLabel();
        c34 = new javax.swing.JLabel();
        c35 = new javax.swing.JLabel();
        c36 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sala2.setBackground(new java.awt.Color(30, 95, 116));
        Sala2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(245, 253, 255));
        jLabel40.setText("FILA \"A\"");
        Sala2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        a25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        a25.setText("|");
        Sala2.add(a25, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, 30));

        a26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        a26.setText("|");
        Sala2.add(a26, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, 30));

        a27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        a27.setText("|");
        Sala2.add(a27, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, 30));

        a28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        a28.setText("|");
        Sala2.add(a28, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, 30));

        a29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        a29.setText("|");
        Sala2.add(a29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, 30));

        a30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        a30.setText("|");
        Sala2.add(a30, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, 30));

        b25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        b25.setText("|");
        Sala2.add(b25, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, 30));

        b26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        b26.setText("|");
        Sala2.add(b26, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, 30));

        b27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        b27.setText("|");
        Sala2.add(b27, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, 30));

        b28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        b28.setText("|");
        Sala2.add(b28, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, 30));

        b29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        b29.setText("|");
        Sala2.add(b29, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, 30));

        b30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        b30.setText("|");
        Sala2.add(b30, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, 30));

        jLabel41.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(245, 253, 255));
        jLabel41.setText("FILA \"B\"");
        Sala2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        c25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        c25.setText("|");
        Sala2.add(c25, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, 30));

        jLabel42.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(245, 253, 255));
        jLabel42.setText("FILA \"C\"");
        Sala2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        c26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        c26.setText("|");
        Sala2.add(c26, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, 30));

        c27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        c27.setText("|");
        Sala2.add(c27, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, 30));

        c28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        c28.setText("|");
        Sala2.add(c28, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, 30));

        c29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        c29.setText("|");
        Sala2.add(c29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, 30));

        c30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        c30.setText("|");
        Sala2.add(c30, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, 30));

        jLabel43.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(245, 253, 255));
        jLabel43.setText("6");
        Sala2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 20, 20));

        jLabel44.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(245, 253, 255));
        jLabel44.setText("5");
        Sala2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 20, 20));

        jLabel45.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(245, 253, 255));
        jLabel45.setText("SALA 1");
        Sala2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 50, 30));

        jLabel46.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(245, 253, 255));
        jLabel46.setText("3");
        Sala2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 20, 20));

        jLabel47.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(245, 253, 255));
        jLabel47.setText("2");
        Sala2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 20, 20));

        jLabel48.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(245, 253, 255));
        jLabel48.setText("1");
        Sala2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 20, 20));

        jLabel49.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(245, 253, 255));
        jLabel49.setText("7");
        Sala2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 20, 20));

        jLabel50.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(245, 253, 255));
        jLabel50.setText("8");
        Sala2.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 20, 20));

        jLabel51.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(245, 253, 255));
        jLabel51.setText("9");
        Sala2.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 20, 20));

        jLabel52.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(245, 253, 255));
        jLabel52.setText("10");
        Sala2.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 20, 20));

        jLabel53.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(245, 253, 255));
        jLabel53.setText("11");
        Sala2.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 20, 20));

        jLabel54.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(245, 253, 255));
        jLabel54.setText("12");
        Sala2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 20, 20));

        a31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        a31.setText("|");
        Sala2.add(a31, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, -1, 30));

        a32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        a32.setText("|");
        Sala2.add(a32, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, -1, 30));

        a33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        a33.setText("|");
        Sala2.add(a33, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, 30));

        a34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        a34.setText("|");
        Sala2.add(a34, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, 30));

        a35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        a35.setText("|");
        Sala2.add(a35, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, 30));

        a36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        a36.setText("|");
        Sala2.add(a36, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, 30));

        b31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        b31.setText("|");
        Sala2.add(b31, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, 30));

        b32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        b32.setText("|");
        Sala2.add(b32, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, 30));

        b33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        b33.setText("|");
        Sala2.add(b33, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, 30));

        b34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        b34.setText("|");
        Sala2.add(b34, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, 30));

        b35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        b35.setText("|");
        Sala2.add(b35, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, 30));

        b36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        b36.setText("|");
        Sala2.add(b36, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, 30));

        c31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        c31.setText("|");
        Sala2.add(c31, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, -1, 30));

        c32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        c32.setText("|");
        Sala2.add(c32, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, 30));

        c33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        c33.setText("|");
        Sala2.add(c33, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, 30));

        c34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        c34.setText("|");
        Sala2.add(c34, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, 30));

        c35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        c35.setText("|");
        Sala2.add(c35, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, 30));

        c36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        c36.setText("|");
        Sala2.add(c36, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, 30));

        jLabel55.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(245, 253, 255));
        jLabel55.setText("4");
        Sala2.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 20, 20));

        jPanel1.add(Sala2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Sala2;
    private javax.swing.JLabel a25;
    private javax.swing.JLabel a26;
    private javax.swing.JLabel a27;
    private javax.swing.JLabel a28;
    private javax.swing.JLabel a29;
    private javax.swing.JLabel a30;
    private javax.swing.JLabel a31;
    private javax.swing.JLabel a32;
    private javax.swing.JLabel a33;
    private javax.swing.JLabel a34;
    private javax.swing.JLabel a35;
    private javax.swing.JLabel a36;
    private javax.swing.JLabel b25;
    private javax.swing.JLabel b26;
    private javax.swing.JLabel b27;
    private javax.swing.JLabel b28;
    private javax.swing.JLabel b29;
    private javax.swing.JLabel b30;
    private javax.swing.JLabel b31;
    private javax.swing.JLabel b32;
    private javax.swing.JLabel b33;
    private javax.swing.JLabel b34;
    private javax.swing.JLabel b35;
    private javax.swing.JLabel b36;
    private javax.swing.JLabel c25;
    private javax.swing.JLabel c26;
    private javax.swing.JLabel c27;
    private javax.swing.JLabel c28;
    private javax.swing.JLabel c29;
    private javax.swing.JLabel c30;
    private javax.swing.JLabel c31;
    private javax.swing.JLabel c32;
    private javax.swing.JLabel c33;
    private javax.swing.JLabel c34;
    private javax.swing.JLabel c35;
    private javax.swing.JLabel c36;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
