/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JframeVenta;

import Cartelera.ObtenerPeliculas;
import ClasesVenta.Asiento;
import ClasesVenta.AsientoSQL;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author CRISTOPHERGUERRA
 */
public class Sala2 extends javax.swing.JPanel {



    public Sala2( ) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Sala1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        aa1 = new javax.swing.JLabel();
        aa2 = new javax.swing.JLabel();
        aa3 = new javax.swing.JLabel();
        aa4 = new javax.swing.JLabel();
        aa5 = new javax.swing.JLabel();
        a6 = new javax.swing.JLabel();
        bb6 = new javax.swing.JLabel();
        bb5 = new javax.swing.JLabel();
        bb4 = new javax.swing.JLabel();
        bb3 = new javax.swing.JLabel();
        bb2 = new javax.swing.JLabel();
        bb1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cc1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cc2 = new javax.swing.JLabel();
        cc3 = new javax.swing.JLabel();
        cc4 = new javax.swing.JLabel();
        cc5 = new javax.swing.JLabel();
        cc6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        aa12 = new javax.swing.JLabel();
        aa11 = new javax.swing.JLabel();
        aa10 = new javax.swing.JLabel();
        aa9 = new javax.swing.JLabel();
        aa8 = new javax.swing.JLabel();
        aa7 = new javax.swing.JLabel();
        bb7 = new javax.swing.JLabel();
        bb8 = new javax.swing.JLabel();
        bb9 = new javax.swing.JLabel();
        bb10 = new javax.swing.JLabel();
        bb11 = new javax.swing.JLabel();
        bb12 = new javax.swing.JLabel();
        cc12 = new javax.swing.JLabel();
        cc11 = new javax.swing.JLabel();
        cc10 = new javax.swing.JLabel();
        cc9 = new javax.swing.JLabel();
        cc8 = new javax.swing.JLabel();
        cc7 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sala1.setBackground(new java.awt.Color(30, 95, 116));
        Sala1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(245, 253, 255));
        jLabel3.setText("FILA \"AA\"");
        Sala1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        aa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        aa1.setText("|");
        Sala1.add(aa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, 30));

        aa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        aa2.setText("|");
        Sala1.add(aa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, 30));

        aa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        aa3.setText("|");
        Sala1.add(aa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, 30));

        aa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        aa4.setText("|");
        Sala1.add(aa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, 30));

        aa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        aa5.setText("|");
        Sala1.add(aa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, 30));

        a6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        a6.setText("|");
        Sala1.add(a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, 30));

        bb6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        bb6.setText("|");
        Sala1.add(bb6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, 30));

        bb5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        bb5.setText("|");
        Sala1.add(bb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, 30));

        bb4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        bb4.setText("|");
        Sala1.add(bb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, 30));

        bb3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        bb3.setText("|");
        Sala1.add(bb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, 30));

        bb2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        bb2.setText("|");
        Sala1.add(bb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, 30));

        bb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        bb1.setText("|");
        Sala1.add(bb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, 30));

        jLabel16.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(245, 253, 255));
        jLabel16.setText("FILA \"BB\"");
        Sala1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        cc1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        cc1.setText("|");
        Sala1.add(cc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, 30));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 253, 255));
        jLabel1.setText("FILA \"CC\"");
        Sala1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        cc2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        cc2.setText("|");
        Sala1.add(cc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, 30));

        cc3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        cc3.setText("|");
        Sala1.add(cc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, 30));

        cc4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        cc4.setText("|");
        Sala1.add(cc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, 30));

        cc5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        cc5.setText("|");
        Sala1.add(cc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, 30));

        cc6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        cc6.setText("|");
        Sala1.add(cc6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, 30));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(245, 253, 255));
        jLabel2.setText("6");
        Sala1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 20, 20));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(245, 253, 255));
        jLabel9.setText("5");
        Sala1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 20, 20));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(245, 253, 255));
        jLabel8.setText("SALA 2");
        Sala1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 50, 30));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(245, 253, 255));
        jLabel7.setText("3");
        Sala1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 20, 20));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(245, 253, 255));
        jLabel6.setText("2");
        Sala1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 20, 20));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(245, 253, 255));
        jLabel5.setText("1");
        Sala1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 20, 20));

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(245, 253, 255));
        jLabel10.setText("7");
        Sala1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 20, 20));

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(245, 253, 255));
        jLabel11.setText("8");
        Sala1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 20, 20));

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(245, 253, 255));
        jLabel12.setText("9");
        Sala1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 20, 20));

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(245, 253, 255));
        jLabel13.setText("10");
        Sala1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 20, 20));

        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(245, 253, 255));
        jLabel14.setText("11");
        Sala1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 20, 20));

        jLabel15.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(245, 253, 255));
        jLabel15.setText("12");
        Sala1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 20, 20));

        aa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        aa12.setText("|");
        Sala1.add(aa12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, -1, 30));

        aa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        aa11.setText("|");
        Sala1.add(aa11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, -1, 30));

        aa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        aa10.setText("|");
        Sala1.add(aa10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, 30));

        aa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        aa9.setText("|");
        Sala1.add(aa9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, 30));

        aa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        aa8.setText("|");
        Sala1.add(aa8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, 30));

        aa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        aa7.setText("|");
        Sala1.add(aa7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, 30));

        bb7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        bb7.setText("|");
        Sala1.add(bb7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, 30));

        bb8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        bb8.setText("|");
        Sala1.add(bb8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, 30));

        bb9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        bb9.setText("|");
        Sala1.add(bb9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, 30));

        bb10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        bb10.setText("|");
        Sala1.add(bb10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, 30));

        bb11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        bb11.setText("|");
        Sala1.add(bb11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, 30));

        bb12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        bb12.setText("|");
        Sala1.add(bb12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, 30));

        cc12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        cc12.setText("|");
        Sala1.add(cc12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, -1, 30));

        cc11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        cc11.setText("|");
        Sala1.add(cc11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, 30));

        cc10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        cc10.setText("|");
        Sala1.add(cc10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, 30));

        cc9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        cc9.setText("|");
        Sala1.add(cc9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, 30));

        cc8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        cc8.setText("|");
        Sala1.add(cc8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, 30));

        cc7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/green_chair.png"))); // NOI18N
        cc7.setText("|");
        Sala1.add(cc7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, 30));

        jLabel39.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(245, 253, 255));
        jLabel39.setText("4");
        Sala1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 20, 20));

        jPanel1.add(Sala1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel Sala1;
    private javax.swing.JLabel a6;
    public static javax.swing.JLabel aa1;
    private javax.swing.JLabel aa10;
    private javax.swing.JLabel aa11;
    private javax.swing.JLabel aa12;
    private javax.swing.JLabel aa2;
    private javax.swing.JLabel aa3;
    private javax.swing.JLabel aa4;
    private javax.swing.JLabel aa5;
    private javax.swing.JLabel aa7;
    private javax.swing.JLabel aa8;
    private javax.swing.JLabel aa9;
    private javax.swing.JLabel bb1;
    private javax.swing.JLabel bb10;
    private javax.swing.JLabel bb11;
    private javax.swing.JLabel bb12;
    private javax.swing.JLabel bb2;
    private javax.swing.JLabel bb3;
    private javax.swing.JLabel bb4;
    private javax.swing.JLabel bb5;
    private javax.swing.JLabel bb6;
    private javax.swing.JLabel bb7;
    private javax.swing.JLabel bb8;
    private javax.swing.JLabel bb9;
    private javax.swing.JLabel cc1;
    private javax.swing.JLabel cc10;
    private javax.swing.JLabel cc11;
    private javax.swing.JLabel cc12;
    private javax.swing.JLabel cc2;
    private javax.swing.JLabel cc3;
    private javax.swing.JLabel cc4;
    private javax.swing.JLabel cc5;
    private javax.swing.JLabel cc6;
    private javax.swing.JLabel cc7;
    private javax.swing.JLabel cc8;
    private javax.swing.JLabel cc9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
