/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Funcion;

import ClasesGlobales.*;
import ClasesInterfaz.*;
import Interfaz.*;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Funcion extends javax.swing.JInternalFrame {
    
    private CRUD crud;
    private int opcionNuevoModificar;
    private FuncionClass funcion;
    private ValidarFuncion validarFuncion;
    private FuncionDias funcionDia;
    private TablaGestion tablaGestion;
    private DefinirConsulta definirConsulta;
    private DefinirTitulos definirTitulos;
    
    
    public Funcion() {
        initComponents();
        crud.InstanciarCRUD().llenar_combo(comboSala, "select * from sala", "num_sala");
        crud.InstanciarCRUD().llenar_combo(comboPelicula, "select * from pelicula", "nombre");
        funcion = new FuncionClass();
        funcionDia = new FuncionDias();
        validarFuncion = new ValidarFuncion();
        bloquearDesbloquearObjetos(0);
        
        tablaGestion = tablaGestion.instanciarTablaGestion();
        definirConsulta = new DefinirConsultaFuncion();
        definirTitulos = new TituloFuncion();
        //EL numero 1 significa que se va buscar respecto al nombre de la pelicula
        //El numero 0 significa que se va a buscar respecto al horario de la pelicula 
        tablaGestion.llenarTabla(definirTitulos.DefinirTitulos(), tablaFuncion, definirConsulta.getConsulta("", funcion, 1));
        diaologDias.setTitle("Dias");
        diaologDias.setSize(340, 170);
        diaologDias.setLocationRelativeTo(Funcion.this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        diaologDias = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDias = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        panelEditar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelEliminar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panelNuevo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        comboPelicula = new javax.swing.JComboBox<>();
        comboSala = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        checkLunes = new javax.swing.JCheckBox();
        checkMartes = new javax.swing.JCheckBox();
        checkMiercoles = new javax.swing.JCheckBox();
        checkJueves = new javax.swing.JCheckBox();
        checkViernes = new javax.swing.JCheckBox();
        checkSabado = new javax.swing.JCheckBox();
        checkDomingo = new javax.swing.JCheckBox();
        checkTodos = new javax.swing.JCheckBox();
        spinerHora = new javax.swing.JSpinner();
        spinerMinuto = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panelCancelar = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        panelAceptar = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        radioHorario = new javax.swing.JRadioButton();
        radioPelicula = new javax.swing.JRadioButton();
        panelBuscar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panelDetalle = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFuncion = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 868, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(29, 45, 80));

        tablaDias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaDias);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout diaologDiasLayout = new javax.swing.GroupLayout(diaologDias.getContentPane());
        diaologDias.getContentPane().setLayout(diaologDiasLayout);
        diaologDiasLayout.setHorizontalGroup(
            diaologDiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaologDiasLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        diaologDiasLayout.setVerticalGroup(
            diaologDiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel5.setBackground(new java.awt.Color(30, 95, 116));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        panelEditar.setBackground(new java.awt.Color(30, 95, 116));
        panelEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickPanel(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entrarPanel(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirPanel(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar_registro.png"))); // NOI18N

        javax.swing.GroupLayout panelEditarLayout = new javax.swing.GroupLayout(panelEditar);
        panelEditar.setLayout(panelEditarLayout);
        panelEditarLayout.setHorizontalGroup(
            panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
            .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEditarLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(13, 13, 13)))
        );
        panelEditarLayout.setVerticalGroup(
            panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
            .addGroup(panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEditarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        panelEliminar.setBackground(new java.awt.Color(30, 95, 116));
        panelEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickPanel(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entrarPanel(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirPanel(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(30, 95, 116));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar_registro.png"))); // NOI18N

        javax.swing.GroupLayout panelEliminarLayout = new javax.swing.GroupLayout(panelEliminar);
        panelEliminar.setLayout(panelEliminarLayout);
        panelEliminarLayout.setHorizontalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
            .addGroup(panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEliminarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelEliminarLayout.setVerticalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
            .addGroup(panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEliminarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        panelNuevo.setBackground(new java.awt.Color(30, 95, 116));
        panelNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickPanel(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entrarPanel(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirPanel(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo_registro.png"))); // NOI18N

        javax.swing.GroupLayout panelNuevoLayout = new javax.swing.GroupLayout(panelNuevo);
        panelNuevo.setLayout(panelNuevoLayout);
        panelNuevoLayout.setHorizontalGroup(
            panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
            .addGroup(panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelNuevoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelNuevoLayout.setVerticalGroup(
            panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
            .addGroup(panelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelNuevoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(panelNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(panelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(panelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(panelNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(19, 59, 92));

        jPanel1.setBackground(new java.awt.Color(30, 95, 116));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nueva Funcion"));

        jLabel1.setText("Precio: ");

        jLabel2.setText("Horario");

        jPanel3.setBackground(new java.awt.Color(30, 95, 116));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dias De Funcion"));

        checkLunes.setText("Lunes");

        checkMartes.setText("Martes");

        checkMiercoles.setText("Miercoles");

        checkJueves.setText("Jueves");

        checkViernes.setText("Viernes");

        checkSabado.setText("Sabado");

        checkDomingo.setText("Domingo");

        checkTodos.setText("Todos");
        checkTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(checkMartes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkLunes, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkMiercoles))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(checkJueves)
                        .addGap(18, 18, 18)
                        .addComponent(checkDomingo))
                    .addComponent(checkViernes)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(checkSabado)
                        .addGap(18, 18, 18)
                        .addComponent(checkTodos)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkLunes)
                    .addComponent(checkJueves, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkDomingo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkMartes)
                    .addComponent(checkViernes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkMiercoles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkSabado)
                    .addComponent(checkTodos))
                .addContainerGap())
        );

        spinerHora.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        spinerMinuto.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hora");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Minuto");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Pelicula");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Sala");

        panelCancelar.setBackground(new java.awt.Color(30, 95, 116));
        panelCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickPanel(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entrarPanel(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirPanel(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N

        javax.swing.GroupLayout panelCancelarLayout = new javax.swing.GroupLayout(panelCancelar);
        panelCancelar.setLayout(panelCancelarLayout);
        panelCancelarLayout.setHorizontalGroup(
            panelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelCancelarLayout.setVerticalGroup(
            panelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelAceptar.setBackground(new java.awt.Color(30, 95, 116));
        panelAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickPanel(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entrarPanel(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirPanel(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aceptar.png"))); // NOI18N

        javax.swing.GroupLayout panelAceptarLayout = new javax.swing.GroupLayout(panelAceptar);
        panelAceptar.setLayout(panelAceptarLayout);
        panelAceptarLayout.setHorizontalGroup(
            panelAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelAceptarLayout.setVerticalGroup(
            panelAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboSala, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(panelAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(spinerHora, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spinerMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(131, 131, 131))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(panelCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboSala, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(spinerHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinerMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))))
        );

        jPanel2.setBackground(new java.awt.Color(30, 95, 116));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Funcion"));

        buttonGroup1.add(radioHorario);
        radioHorario.setText("Horario");

        buttonGroup1.add(radioPelicula);
        radioPelicula.setText("Pelicula");

        panelBuscar.setBackground(new java.awt.Color(30, 95, 116));
        panelBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickPanel(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entrarPanel(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirPanel(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(30, 95, 116));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar_registro.png"))); // NOI18N

        javax.swing.GroupLayout panelBuscarLayout = new javax.swing.GroupLayout(panelBuscar);
        panelBuscar.setLayout(panelBuscarLayout);
        panelBuscarLayout.setHorizontalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBuscarLayout.setVerticalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelDetalle.setBackground(new java.awt.Color(30, 95, 116));
        panelDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickDetalle(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entrarDetalle(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirDetalle(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/view_grid_detail_icon_154644.png"))); // NOI18N

        javax.swing.GroupLayout panelDetalleLayout = new javax.swing.GroupLayout(panelDetalle);
        panelDetalle.setLayout(panelDetalleLayout);
        panelDetalleLayout.setHorizontalGroup(
            panelDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
            .addGroup(panelDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDetalleLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel13)
                    .addContainerGap(7, Short.MAX_VALUE)))
        );
        panelDetalleLayout.setVerticalGroup(
            panelDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
            .addGroup(panelDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDetalleLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel13)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioPelicula)
                    .addComponent(radioHorario))
                .addGap(53, 53, 53)
                .addComponent(panelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(16, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(radioHorario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioPelicula))
                            .addComponent(panelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tablaFuncion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaFuncion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickTabla(evt);
            }
        });
        jScrollPane1.setViewportView(tablaFuncion);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void bloquearDesbloquearObjetos(int opcion) {
        boolean bloquear = false;
        //si se manda una opcion que sea igual a 1 se bloquearan los objetos
        if (opcion == 1) {
            bloquear = true;
        }
        
        txtPrecio.setEnabled(bloquear);
        
        comboPelicula.setEnabled(bloquear);
        comboSala.setEnabled(bloquear);
        
        panelAceptar.setEnabled(bloquear);
        panelCancelar.setEnabled(bloquear);
        
        spinerHora.setEnabled(bloquear);
        spinerMinuto.setEnabled(bloquear);
        
        checkDomingo.setEnabled(bloquear);
        checkJueves.setEnabled(bloquear);
        checkLunes.setEnabled(bloquear);
        checkMartes.setEnabled(bloquear);
        checkMiercoles.setEnabled(bloquear);
        checkSabado.setEnabled(bloquear);
        checkTodos.setEnabled(bloquear);
        checkViernes.setEnabled(bloquear);
        
       //el relativo respecto al internal frame
       //diaologDias.setUndecorated(true);//Le quita el boron de cerrar
    }
    
    public void RelacionarDia() {
        String query;
        if (checkDomingo.isSelected()) {
            funcionDia.setIdDia(7);
            funcionDia.actualizarValues();
            query = funcionDia.getAdminConsulta().queryInsertar(funcionDia.getValues(), funcionDia.getParametros(), funcionDia.getNombre());
            System.out.println(query);
            crud.InstanciarCRUD().EjecutarInstruccion(query, 0);
        }
        if (checkSabado.isSelected()) {
            funcionDia.setIdDia(6);
            funcionDia.actualizarValues();
            query = funcionDia.getAdminConsulta().queryInsertar(funcionDia.getValues(), funcionDia.getParametros(), funcionDia.getNombre());
            System.out.println(query);
            crud.InstanciarCRUD().EjecutarInstruccion(query, 0);
        }
        if (checkViernes.isSelected()) {
            funcionDia.setIdDia(5);
            funcionDia.actualizarValues();
            query = funcionDia.getAdminConsulta().queryInsertar(funcionDia.getValues(), funcionDia.getParametros(), funcionDia.getNombre());
            System.out.println(query);
            crud.InstanciarCRUD().EjecutarInstruccion(query, 0);
        }
        if (checkJueves.isSelected()) {
            funcionDia.setIdDia(4);
            funcionDia.actualizarValues();
            query = funcionDia.getAdminConsulta().queryInsertar(funcionDia.getValues(), funcionDia.getParametros(), funcionDia.getNombre());
            System.out.println(query);
            crud.InstanciarCRUD().EjecutarInstruccion(query, 0);
        }
        if (checkMiercoles.isSelected()) {
            funcionDia.setIdDia(3);
            funcionDia.actualizarValues();
            query = funcionDia.getAdminConsulta().queryInsertar(funcionDia.getValues(), funcionDia.getParametros(), funcionDia.getNombre());
            System.out.println(query);
            crud.InstanciarCRUD().EjecutarInstruccion(query, 0);
        }
        if (checkMartes.isSelected()) {
            funcionDia.setIdDia(2);
            funcionDia.actualizarValues();
            query = funcionDia.getAdminConsulta().queryInsertar(funcionDia.getValues(), funcionDia.getParametros(), funcionDia.getNombre());
            System.out.println(query);
            crud.InstanciarCRUD().EjecutarInstruccion(query, 0);
        }
        if (checkLunes.isSelected()) {
            funcionDia.setIdDia(1);
            funcionDia.actualizarValues();
            query = funcionDia.getAdminConsulta().queryInsertar(funcionDia.getValues(), funcionDia.getParametros(), funcionDia.getNombre());
            System.out.println(query);
            crud.InstanciarCRUD().EjecutarInstruccion(query, 0);
        }
        
    }
    

    private void checkTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTodosActionPerformed
        boolean activar = false;
        if (checkTodos.isSelected()) {
            activar = true;
        }
        checkDomingo.setSelected(activar);
        checkJueves.setSelected(activar);
        checkLunes.setSelected(activar);
        checkMartes.setSelected(activar);
        checkMiercoles.setSelected(activar);
        checkSabado.setSelected(activar);
        checkViernes.setSelected(activar);
    }//GEN-LAST:event_checkTodosActionPerformed

    private void entrarPanel(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarPanel
        if (evt.getSource() == panelNuevo) {
            panelNuevo.setBackground(new Color(29, 45, 80));
            panelNuevo.setCursor(new Cursor(Cursor.HAND_CURSOR));
            
        }
        if (evt.getSource() == panelEditar) {
            panelEditar.setBackground(new Color(29, 45, 80));
            panelEditar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }
        if (evt.getSource() == panelEliminar) {
            panelEliminar.setBackground(new Color(29, 45, 80));
            panelEliminar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }
        if (evt.getSource() == panelAceptar) {
            panelAceptar.setBackground(new Color(29, 45, 80));
            panelAceptar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }
        if (evt.getSource() == panelCancelar) {
            panelCancelar.setBackground(new Color(29, 45, 80));
            panelCancelar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }
        if (evt.getSource() == panelBuscar) {
            panelBuscar.setBackground(new Color(29, 45, 80));
            panelBuscar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }
    }//GEN-LAST:event_entrarPanel

    private void salirPanel(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirPanel
        if (evt.getSource() == panelNuevo) {
            panelNuevo.setBackground(new Color(30, 95, 116));
            
        }
        if (evt.getSource() == panelEditar) {
            panelEditar.setBackground(new Color(30, 95, 116));
            
        }
        if (evt.getSource() == panelEliminar) {
            panelEliminar.setBackground(new Color(30, 95, 116));
            
        }
        if (evt.getSource() == panelAceptar) {
            panelAceptar.setBackground(new Color(30, 95, 116));
            
        }
        if (evt.getSource() == panelCancelar) {
            panelCancelar.setBackground(new Color(30, 95, 116));
            
        }
        if (evt.getSource() == panelBuscar) {
            panelBuscar.setBackground(new Color(30, 95, 116));
            
        }
    }//GEN-LAST:event_salirPanel

    private void clickPanel(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickPanel
        if (evt.getSource() == panelNuevo) {
            bloquearDesbloquearObjetos(1);
            opcionNuevoModificar = 1;
        }
        if (evt.getSource() == panelEditar) {
            opcionNuevoModificar = 0;
            
        }
        if (evt.getSource() == panelEliminar) {
            
        }
        if (evt.getSource() == panelAceptar) {
            if (opcionNuevoModificar == 1) {
                if (validarFuncion.ValidarDatos(txtPrecio.getText()) >= 0) {
                    funcion.setHorario(validarFuncion.FormarHora(spinerHora, spinerMinuto));
                    funcion.setPrecio(Float.valueOf(txtPrecio.getText()));
                    
                    funcion.setIdSala(Integer.parseInt(crud.InstanciarCRUD().getValor("select * from sala where num_sala =" + comboSala.getSelectedItem().toString(), "idSala")));
                    
                    funcion.setIdPelicula(Integer.parseInt(crud.InstanciarCRUD().getValor("select * from  pelicula where nombre = '" + comboPelicula.getSelectedItem().toString() + "'", "idPelicula")));
                    funcion.actualizarValues();
                    
                    String query = funcion.getAdminConsulta().queryInsertar(funcion.getValues(), funcion.getParametros(), funcion.getNombre());
                    //System.out.println(query);
                    crud.InstanciarCRUD().EjecutarInstruccion(query, 0);
                    // System.out.println(crud.InstanciarCRUD().getUltimoID("idFuncion","funcion"));
                    funcionDia.setIdFuncion(crud.InstanciarCRUD().getUltimoID("idFuncion", "funcion"));
                    this.RelacionarDia();
                    JOptionPane.showMessageDialog(null, "Funcion ingresada correctamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                    
                }
            } else {
                
            }
        }
        if (evt.getSource() == panelCancelar) {
            bloquearDesbloquearObjetos(0);
        }
        if (evt.getSource() == panelBuscar) {
            
        }
    }//GEN-LAST:event_clickPanel

    private void clickTabla(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickTabla
        

    }//GEN-LAST:event_clickTabla

    private void clickDetalle(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickDetalle
        int fila = tablaFuncion.getSelectedRow();
        if (fila >= 0) {
            funcion.getAdminConsulta().setWhere("where f.Precio =" + String.valueOf(tablaFuncion.getValueAt(fila, 0)) + " and s.num_sala =" + String.valueOf(tablaFuncion.getValueAt(fila, 2))
                    + " and p.nombre ='" + String.valueOf(tablaFuncion.getValueAt(fila, 3)) + "' and f.Horario='" + String.valueOf(tablaFuncion.getValueAt(fila, 1)) + "'");
            
            funcion.getAdminConsulta().setQuery("select f.idFuncion as id from funcion as f\n"
                    + "inner join sala as s on s.idSala = f.Sala_idSala\n"
                    + "inner join pelicula as p on p.idPelicula = f.Pelicula_idPelicula " + funcion.getAdminConsulta().getWhere());

            // System.out.println(funcion.getAdminConsulta().getQuery());
            funcion.setId(crud.InstanciarCRUD().getValor(funcion.getAdminConsulta().getQuery(), "id"));
            String[] tituloDia = {"dia"};
            funcion.getAdminConsulta().setQuery("select d.dia as dia from detalle_funcion_dias as df\n"
                    + "inner join dias as d on d.iddias_funcion = df.dias_iddias_funcion\n"
                    + "inner join funcion as f on f.idFuncion = df.funcion_idHorario ");
            funcion.getAdminConsulta().setWhere("where f.idFuncion = "+funcion.getId());
           
            tablaGestion.llenarTabla(tituloDia, tablaDias,funcion.getAdminConsulta().getQuery()+funcion.getAdminConsulta().getWhere());
            diaologDias.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una funcion", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_clickDetalle

    private void entrarDetalle(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarDetalle
        panelDetalle.setBackground(new Color(29, 45, 80));
        panelDetalle.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_entrarDetalle

    private void salirDetalle(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirDetalle
        panelDetalle.setBackground(new Color(30, 95, 116));
    }//GEN-LAST:event_salirDetalle


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkDomingo;
    private javax.swing.JCheckBox checkJueves;
    private javax.swing.JCheckBox checkLunes;
    private javax.swing.JCheckBox checkMartes;
    private javax.swing.JCheckBox checkMiercoles;
    private javax.swing.JCheckBox checkSabado;
    private javax.swing.JCheckBox checkTodos;
    private javax.swing.JCheckBox checkViernes;
    private javax.swing.JComboBox<String> comboPelicula;
    private javax.swing.JComboBox<String> comboSala;
    private javax.swing.JDialog diaologDias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelAceptar;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelCancelar;
    private javax.swing.JPanel panelDetalle;
    private javax.swing.JPanel panelEditar;
    private javax.swing.JPanel panelEliminar;
    private javax.swing.JPanel panelNuevo;
    private javax.swing.JRadioButton radioHorario;
    private javax.swing.JRadioButton radioPelicula;
    private javax.swing.JSpinner spinerHora;
    private javax.swing.JSpinner spinerMinuto;
    private javax.swing.JTable tablaDias;
    private javax.swing.JTable tablaFuncion;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
